### ISSUE TITLE
shared object not loaded

### ISSUE THREAD

**Issue by FelicienLL** [FelicienLL/mapbayr#130]
Test if mrgsolve shared object is loaded, and return an explicit error message if not. Currently, if the SO is missing, the optimizer is just crashing.

**Comment by kylebaron** [comment]
mrgsolve should try to load the shared object if it isn't loaded when you go to simulate. You can check for the shared object here (I think you are already pulling this list)

```r
as.list(mod)$sodll
```

So maybe something like this

```r
x <- as.list(mod)
stopifnot(file.exists(x$sodll))
```
and optionally 

```r
loadso(mod)
```

But this step should happen under the hood if the so isn't loaded.

**Comment by kylebaron** [comment]
Oh ... ok; then maybe you could just do `try(loadso(mod))` and check that.
