### ISSUE TITLE
Error if dose-related parameters > interdose interval

### ISSUE THREAD

**Issue by FelicienLL** [FelicienLL/mapbayr#142]
``` r
library(mrgsolve)
#> 
#> Attachement du package : 'mrgsolve'
#> L'objet suivant est masqué depuis 'package:stats':
#> 
#>     filter
library(mapbayr)
code141 <- "
$PARAM ETA1 = 0, ETA2 = 0
$CMT GUT CENT
$OMEGA .5 .5
$SIGMA .04 0
$MAIN
double KA = 1 ;
double CL = 1 ;
double V = 30 ;
double ALAG1 = 5.0 * exp(ETA(1) + ETA1) ;
double D1 = 5.0 * exp(ETA(2) + ETA2) ;
ALAG_GUT = ALAG1 ; 
D_GUT = D1 ; 
$PKMODEL ncmt = 1, depot = TRUE
$ERROR
double DV = CENT/V *(1 + EPS(1)) ;
$CAPTURE DV ALAG1 D1
"
mod141 <- mcode("mod141",code141)
#> Building mod141 ...
#> done.
dat141 <- mod141 %>% 
  adm_lines(amt = 1000, cmt = 1, ss = 1, ii = 24) %>% 
  obs_lines(time = c(1,4,12), DV = c(26, 52, 41), cmt= 2) %>% 
  get_data()
mapbayest(mod141, dat141)
#> Error: ALAG_CMT greater than ii on ss record.

argofv141 <- c(
  preprocess.ofv.fix(mod141, dat141),
  preprocess.ofv.id(mod141, dat141)
)

do_compute_ofv(eta = c(ETA1 = -2, ETA2 = -2), argofv141)
#> [1] 29.41394
do_compute_ofv(eta = c(ETA1 = 2, ETA2 = 2), argofv141)
#> Error: ALAG_CMT greater than ii on ss record.
```

<sup>Created on 2022-07-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kylebaron** [comment]
@FelicienLL - 

I made this error a while ago because I wasn't sure what the behavior should be. I know you'll have to deal with this in mapbayr for now, but I'd like to get a fix working upstream so this gets handled naturally. What do you think?

Kyle

**Comment by FelicienLL** [comment]
Hi Kyle, 
Thanks for your feedback.
Of course, it would be nice to have predictions instead of this error message but I imagine it is pretty complicated to implement. And, to be honest, in my opinion it is not such a *big* deal. I almost never expect to estimate/simulate a lag time or a duration infusion (say) longer than 24h. This error only shows up because the optimizer make an iteration far of the typical value, and this behaviour is easy to correct within mapbayr. In the context of simulations, the error also comes sometimes, when a large number of patients are simulated, but again, pretty easy to correct with simeps() inside the model code for instance. So, to sum it up, I would not say it is a top-priority error to fix, at least for mapbayr. However, if you plan to fix it, I'd be happy to help if I can... although I don't even know how NONMEM behaves in this situation. 

Félicien

**Comment by kylebaron** [comment]
Ok; I'm sure I did a simulation with NONMEM a long time ago to try to figure it out. I'll try to get that going again and see if I can handle this better. 

I get annoyed by this too when simulating with ETA on ALAG (as you have in the example) and you can have this happen with no way to intervene in the simulation case.
