### ISSUE TITLE
check fails with mrgsolve 1.0.5

### ISSUE THREAD

**Issue by FelicienLL** [FelicienLL/mapbayr#144]
See https://github.com/metrumresearchgroup/mrgsolve/pull/1013
I can confirm the fail of R CMD check, the fact that is due to a bug in as.list and/or TOUCHFUNS, and that the new branch (up to `f5c4770`) fixes it.

**Comment by FelicienLL** [comment]
Fixed in 1.0.6

**Comment by kylebaron** [comment]
Thanks for following this @FelicienLL.
