### ISSUE TITLE
Error: cannot evaluate function at initial parameters 

### ISSUE THREAD

**Issue by jkamp91** [FelicienLL/mapbayr#88]
Hi,

I’m trying to run a mrgsolve model (oral 2 compartment model with depot compartment) with the mapbayest() function in R. Although some other simple test models ran successfully, i now encounter the following error:

error in optimx.check(pas, optcfg$ufn, optcf$ugr, optfg$uhess, lower, : cannot evaluate function at initial parameters.

I already thoroughly check the mrgsolve model code and test data file for errors and compared the code with that of a working model.

Does anyone know what could be causing this error?

Thanks!

jasper

**Comment by FelicienLL** [comment]
Hi Jasper,
Thanks for your report. This error message comme from the optimizer but is not very specific, so it is hard to tell what is wrong now. Could you post your model code and a bit of data ? 
Thx. Félicien

**Comment by jkamp91** [comment]
Hi Felicien,

Here's a small test dataset i used to see if i could get the model running:

[Prograft_test.csv](https://github.com/FelicienLL/mapbayr/files/7149397/Prograft_test.csv)

Here's the mrgsolve model code:

$PARAM @annotated
TVKA	: 0.57 : Absorption constant (1/h)
TVV2	: 12.6  : Central volume (L)
TVCL	: 6.5  : Elimination clearance (L/h)
TVV3	: 93.5: Peripheral volume of distribution (L) 
TVQ  	: 35.87: Intercompartmental clearance (L/h)
TVALAG  : 0.9 : lag time

ETA1 : 0 : KA
ETA2 : 0 : V2
ETA3 : 0 : CL
ETA4 : 0 : V3
ETA5 : 0 : Q
ETA6 : 0 : alag

$OMEGA
0.03 // BSVKA
0.1 // BSVV2
0.8 // BSVCL
0.6  // BSVV3
1.1  // BSQ
0.1 // Alag

$SIGMA @annotated
PROP : 0.0018 : Proportional residual error
ADD : 0 : additive

$CMT @annotated
GUT       :    Dosing compartment [ADM];
CENT      :    Central compartment [OBS];
PERI    	: peripheral             
 
$MAIN
double KA         = TVKA * exp(ETA1 + ETA(1));
double V2         = TVV2 * exp(ETA2 + ETA(2));
double CL         = TVCL * exp(ETA3 + ETA(3));
double V3         = TVV3 *  exp(ETA4 + ETA(4));
double Q          = TVQ  *  exp(ETA5 + ETA(5));
double LG        = TVALAG * exp(ETA6 + ETA(6));

double K10        = CL/V2;
double K12        = Q/V2;
double K21        = Q/V3;

ALAG_GUT = LG;

$PKMODEL ncmt=2, depot=TRUE

$TABLE
double DV = (CENT / V2) * (1 + EPS(1)) ;
 
$CAPTURE DV

To load/build the model, and to run it, I used the R code:
prograft.code <- mread("Prograft_code.cpp")
prograft_run <- mapbayest(x = prograft.code, data = prograft_data)

I'm new to using mapbayr, so hopefully it's enough information!

- Jasper

**Comment by FelicienLL** [comment]
Hello,
I think there is a problem of units between your dose and concentrations, because these concentrations cannot be observed at these dose levels (see below the level of concentrations when we simulate typical profiles from your data): 

``` r
prograft.code %>% 
 data_set(prograft_data) %>% 
 zero_re() %>% 
 mrgsim()

#> Model:  mod 
#> Dim:    30 x 6 
#> Time:   0 to 12 
#> ID:     5 
#>     ID TIME      GUT    CENT    PERI       DV
#> 1:   1    0 0.000000 0.00000 0.00000 0.000000
#> 2:   1    1 1.889188 0.09413 0.01410 0.007470
#> 3:   1    2 1.068384 0.25341 0.55791 0.020112
#> 4:   1    3 0.604198 0.21856 0.93525 0.017346
#> 5:   1    4 0.341690 0.19207 1.11876 0.015243
#> 6:   1   12 0.003575 0.11068 0.94902 0.008784
#> 7:   2    0 0.000000 0.00000 0.00000 0.000000
#> 8:   2    1 3.778376 0.18825 0.02819 0.014941
```
You can apply the scaling on the model with:
``` c
$TABLE
double DV = (CENT / V2) * (1 + EPS(1))  * 1000
```
After that, the estimation process runs ok to me:

```r
est <- mapbayest(mod, dat)
#> 
#> ID 1... done.
#> 
#> ID 2...
#> Warning: 
#> Error in optimization. Reset with new initial values: 0.100632 -0.189599 1.027809 0.636449 0.240931 -0.048723
#>  done.
#> 
#> ID 3... done.
#> 
#> ID 4... done.
#> 
#> ID 5...
#> Warning: 
#> Error in optimization. Reset with new initial values: -0.042888 -0.602792 0.736928 1.601194 1.295077 -0.33663
#>  done.
#>  
#>  Model:  mod 
#>  ID : 5  individual(s).
#>  OBS: 25  observation(s).
#>  ETA: 6  parameter(s) to estimate.
#>  
#>  Estimates: 
#>    ID        ETA1        ETA2       ETA3       ETA4       ETA5        ETA6
#>  1  1  0.05017905 -0.01371918 -0.8896315  0.4684982  0.4101510 -0.08473247
#>  2  2 -0.03386614  0.02134100  0.5233323  1.1134356  0.8758676  0.03443696
#>  3  3  0.01407659 -0.02587314  1.0149800  0.1220645  1.7169031 -0.11473024
#>  4  4  0.09895805 -0.24673717 -0.8644935 -1.1128518 -0.1783502 -0.37743025
#>  5  5 -0.02032540  0.01258105  1.5168546  1.0288570  2.1589499  0.01032285

#>  Output (30 lines): 
#>    ID time evid amt cmt mdv DV     IPRED      PRED       ETA1        ETA2       ETA3      ETA4     ETA5        ETA6
#>  1  1    0    1   2   1   1 NA  0.000000  0.000000 0.05017905 -0.01371918 -0.8896315 0.4684982 0.410151 -0.08473247
#>  2  1    1    0   0   2   0 11 10.975496  7.470338 0.05017905 -0.01371918 -0.8896315 0.4684982 0.410151 -0.08473247
#>  3  1    2    0   0   2   0 16 15.912407 20.111965 0.05017905 -0.01371918 -0.8896315 0.4684982 0.410151 -0.08473247
#>  4  1    3    0   0   2   0 14 13.765472 17.345720 0.05017905 -0.01371918 -0.8896315 0.4684982 0.410151 -0.08473247
#>  5  1    4    0   0   2   0 12 12.472799 15.243425 0.05017905 -0.01371918 -0.8896315 0.4684982 0.410151 -0.08473247
#>  6  1   12    0   0   2   0 10  9.802558  8.783766 0.05017905 -0.01371918 -0.8896315 0.4684982 0.410151 -0.08473247
```

Does it fix your issue? I'm surprised that I did not met the "cannot evaluate function at initial parameters" error though. If you still have this error message, do not hesitate to post the code that renders this error in form of a [reprex](https://github.com/tidyverse/reprex) so that we can really see under which conditions it happens.
Félicien

**Comment by jkamp91** [comment]
Hi,

I corrected the scaling factor (Thanks!) as described above. However, the error keeps popping up.

``` r
prograft_run <- mapbayest(x = prograft.code, data = prograft_data)
#> Error in mapbayest(x = prograft.code, data = prograft_data): could not find function "mapbayest"
```

<sup>Created on 2021-09-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Interestingly, the reprex gives the error "Error is mapbayest", while the true error, as shown in the console is:

ID 1...Error in optimx.check(par, optcfg$ufn, optcfg$ugr, optcfg$uhess, lower,  : 
  Cannot evaluate function at initial parameters

(My appologies for not putting this in a reprex. Reprex somehow does not show this error correctly).

The above "Error in mapbayest" is a bit strange, since I succefully attached the mapbayr package with:

``` r
library(mapbayr)
```

<sup>Created on 2021-09-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Again, for an other, simple i.v. model, the mapbayest function did work properly.

-Jasper

**Comment by FelicienLL** [comment]
Ok, I think `mapbayest` could not be found because the reprex wasn't probably written the way it is supposed to be. Briefly, {reprex} executes the code in an independant R session, so this is why you have to insert all the code in it, from package attachment to the execution of the lines that returns the error. If you manage to build one properly, it would be helpful I think.
Otherwise, we can still test other hypotheses: 

- Does it also crash you just simulate from your model and data with  `mrgsolve::mrgsim(x = prograft.code, data = prograft_data)`?
- Has the dataset been correctly imported from .csv to R? Are all the columns numeric, especially DV which has "." that should be read as `NA`? see `str(prograft_data)` and `head(prograft_data)`.
- Could you test without ID1 in your data, to see if the problem comes from this individual in particular?
- Could you test without any lag time in your model?

Thank you

Félicien

**Comment by jkamp91** [comment]
Hi Felicien,

Many thanks for posting several hypotheses! It seemed indeed that the data import step caused all the trouble. Changing all columns to numeric solved the problem.

Thanks again for your help!

Jasper

**Comment by FelicienLL** [comment]
Ok, nice to hear that! 
I already planned future modifications to handle non-numeric columns more correctly: I'll keep your issue in mind, so thanks for reporting.
Have a nice day

Félicien
